services:
  mongodb:
    image: mongo:4.4
    container_name: moviet-mongodb
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - moviet_db_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb-setup:
    image: mongo:4.4
    container_name: moviet-mongodb-setup
    depends_on:
      mongodb:
        condition: service_healthy
    entrypoint: [ "bash", "-c", "mongo --host moviet-mongodb:27017 --eval 'rs.initiate() || db.stats()'" ]

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: moviet-auth-service
    ports:
      - "8080:8080"
    env_file:
      - ./auth-service/.env
    depends_on:
      - mongodb

  movie-service:
    build:
      context: .
      dockerfile: movie-service/Dockerfile
    container_name: moviet-movie-service
    ports:
      - "8081:8081"
    env_file:
      - ./movie-service/.env
    depends_on:
      - mongodb

  prisma-studio:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: moviet-prisma-studio
    ports:
      - "5555:5555"
    command: npx prisma studio --port 5555 --browser none
    env_file:
      - ./auth-service/.env
    depends_on:
      - mongodb
      - auth-service

volumes:
  moviet_db_data:
