services:
  gateway:
    image: nginx:alpine
    container_name: moviet-gateway
    ports:
      - "4000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - movie-service
      - payment-service

  mongodb:
    image: mongo:4.4
    container_name: moviet-mongodb
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - moviet_db_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb-setup:
    image: mongo:4.4
    container_name: moviet-mongodb-setup
    depends_on:
      mongodb:
        condition: service_healthy
    entrypoint: [ "bash", "-c", "mongo --host moviet-mongodb:27017 --eval 'rs.initiate() || db.stats()'" ]

  seed-setup:
    build:
      context: .
      dockerfile: Dockerfile.seed
    container_name: moviet-seed-setup
    depends_on:
      mongodb-setup:
        condition: service_completed_successfully
    command: npm run seed
    env_file:
      - ./auth-service/.env
      - ./movie-service/.env

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: moviet-auth-service
    ports:
      - "8080:8080"
    env_file:
      - ./auth-service/.env
    depends_on:
      seed-setup:
        condition: service_completed_successfully

  movie-service:
    build:
      context: .
      dockerfile: movie-service/Dockerfile
    container_name: moviet-movie-service
    ports:
      - "8081:8081"
    env_file:
      - ./movie-service/.env
    depends_on:
      seed-setup:
        condition: service_completed_successfully

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    container_name: moviet-payment-service
    ports:
      - "8082:8082"
    env_file:
      - ./payment-service/.env
    depends_on:
      seed-setup:
        condition: service_completed_successfully

  prisma-studio-auth:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: moviet-prisma-studio-auth
    ports:
      - "5555:5555"
    command: npx prisma studio --port 5555 --browser none
    env_file:
      - ./auth-service/.env
    depends_on:
      - mongodb
      - auth-service

  prisma-studio-movie:
    build:
      context: .
      dockerfile: movie-service/Dockerfile
    container_name: moviet-prisma-studio-movie
    ports:
      - "5556:5556"
    command: npx prisma studio --port 5556 --browser none
    env_file:
      - ./movie-service/.env
    depends_on:
      - mongodb
      - movie-service

volumes:
  moviet_db_data:
